project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "beco3310/*.qmd"
  resources:
    - cv.pdf
    - publications/**
    - images/research/**
    - beco3310/pdfs/**
    - beco3310/hw_images/**
    - CNAME
    - logo.png
    - favicon.png

website:
  title: "Leonel A. Regalado Cardoso"
  description: "Academic Website"
  site-url: https://leoregalado.com
  favicon: favicon.png
  open-graph:
    image: logo.png
  twitter-card:
    image: logo.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: explore-research.qmd
        text: Explore My Research
      - href: teaching.qmd
        text: Teaching
      - href: presentations.qmd
        text: Presentations
      - href: cv.pdf
        text: CV
        target: _blank
    right:
      - icon: envelope
        href: mailto:lregalad@ttu.edu
      - icon: github
        href: https://github.com/leoregalado17
      - icon: linkedin
        href: https://www.linkedin.com/in/leonel-regalado/
  page-footer:
    center: "© 2026 Leonel A. Regalado Cardoso. Built with [Quarto](https://quarto.org/)."

format:
  html:
    theme:
      light: [cosmo, custom.scss]
      dark: [darkly, custom.scss]
    css: styles.css
    toc: false
