---
title: "Presentations"
---

## Academic Conferences

**2026**

- Association for Private Enterprise Education — Las Vegas, NV
- Public Choice Society — San Antonio, TX

**2025**

- Southern Economic Association — Tampa, FL
- Association for Private Enterprise Education — Guatemala City, Guatemala

**2024**

- Association for Private Enterprise Education — Las Vegas, NV

**2023**

- Association for Private Enterprise Education — Cancún, Mexico

**2022**

- Southern Economic Association — Fort Lauderdale, FL
- Association for Private Enterprise Education — Las Vegas, NV

---

## Invited Talks

- Jul. 2026. "How to Perform Research Effectively," Advanced Economics Seminar, Universidad Francisco Marroquín, Guatemala.
- Apr. 2025. "Emigration and Origin Country Institutions," Universidad Francisco Marroquín, Guatemala.

---

## Workshops

- 2026 — Economic Freedom and Human Flourishing: A Graduate Papers Workshop, Institute for Humane Studies & University of Wisconsin–La Crosse — La Crosse, WI
- 2025 — UFM Prosperity Lab Research Workshop on Development Economics & Entrepreneurship — Guatemala City, Guatemala
- 2025 — Idea & Paper Development Workshop, Institute for the Study of Free Enterprise, Oklahoma State University — Stillwater, OK
